# Generated by Django 5.1.7 on 2026-09-24 13:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_options_order_contact_phone_and_more"),
        ("restaurants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("owner_reply", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={"ordering": ["category", "name"]},
        ),
        migrations.AlterModelOptions(
            name="restaurant",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="menuitem",
            name="calories",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="category",
            field=models.CharField(default="Mains", max_length=50),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="image_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_gluten_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_vegan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_vegetarian",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="spice_level",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(3)]
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="closes_at",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="cuisine",
            field=models.CharField(
                choices=[
                    ("american", "American"),
                    ("bangladeshi", "Bangladeshi"),
                    ("chinese", "Chinese"),
                    ("desserts", "Desserts"),
                    ("healthy", "Healthy"),
                    ("indian", "Indian"),
                    ("italian", "Italian"),
                    ("japanese", "Japanese"),
                    ("korean", "Korean"),
                    ("mexican", "Mexican"),
                    ("middle_eastern", "Middle Eastern"),
                    ("thai", "Thai"),
                    ("cafe", "Cafe"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=6),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="image_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="is_accepting_orders",
            field=models.BooleanField(
                default=True,
                help_text="Owners can pause new orders when the kitchen is busy.",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="min_order",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="opens_at",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="prep_time_minutes",
            field=models.PositiveSmallIntegerField(
                default=20,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(180),
                ],
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="price_level",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "$"), (2, "$$"), (3, "$$$")], default=2
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="tags",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Comma separated, e.g. "burgers, late night"',
                max_length=200,
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["restaurant", "is_available"],
                name="restaurants_restaur_1087ee_idx",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "restaurant"), name="unique_favorite"
            ),
        ),
    ]
